/**
 * Report Module
 *
 * Generates HTML reports with inline CSS for portability
 */

import { Report, ReportSummary, Finding } from '../types';

/**
 * Escape HTML special characters to prevent XSS
 *
 * @param text - Text to escape
 * @returns Escaped text safe for HTML
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '\x26amp;')
    .replace(/</g, '\x26lt;')
    .replace(/>/g, '\x26gt;')
    .replace(/"/g, '\x26quot;')
    .replace(/'/g, '\x26#39;');
}

/**
 * Generate HTML report from findings
 * 
 * @param report - Complete report data
 * @returns HTML string with inline CSS
 */
export function generateHTMLReport(report: Report): string {
  // TODO: Implement full HTML report generation
  console.log(`Generating HTML report for ${report.metadata.projectName}`);
  
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SupplyShield Security Report - ${escapeHtml(report.metadata.projectName)}</title>
  <style>
    ${getInlineCSS()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🛡️ SupplyShield Security Report</h1>
      <div class="metadata">
        <p><strong>Project:</strong> ${escapeHtml(report.metadata.projectName)} v${escapeHtml(report.metadata.projectVersion)}</p>
        <p><strong>Scan Date:</strong> ${escapeHtml(new Date(report.metadata.scanDate).toLocaleString())}</p>
        <p><strong>SupplyShield Version:</strong> ${escapeHtml(report.metadata.supplyShieldVersion)}</p>
      </div>
    </header>
    
    <section class="summary">
      <h2>Summary</h2>
      ${generateSummaryHTML(report.summary)}
    </section>
    
    <section class="findings">
      <h2>Findings (${report.findings.length})</h2>
      ${generateFindingsHTML(report.findings)}
    </section>
    
    <footer>
      <p>Generated by SupplyShield v${escapeHtml(report.metadata.supplyShieldVersion)}</p>
      <p>Report generated at ${escapeHtml(report.generatedAt)}</p>
    </footer>
  </div>
</body>
</html>
  `.trim();
  
  return html;
}

/**
 * Get inline CSS for the report
 * 
 * @returns CSS string
 */
function getInlineCSS(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }
    
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    
    header {
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    h1 {
      color: #1e40af;
      font-size: 2.5em;
      margin-bottom: 15px;
    }
    
    h2 {
      color: #1e40af;
      font-size: 1.8em;
      margin: 30px 0 15px 0;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
    }
    
    .metadata {
      background: #f9fafb;
      padding: 15px;
      border-radius: 5px;
      margin-top: 15px;
    }
    
    .metadata p {
      margin: 5px 0;
    }
    
    .summary {
      margin: 30px 0;
    }
    
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-top: 20px;
    }
    
    .summary-card {
      background: #f9fafb;
      padding: 20px;
      border-radius: 5px;
      border-left: 4px solid #6b7280;
    }
    
    .summary-card.critical {
      border-left-color: #dc2626;
      background: #fef2f2;
    }
    
    .summary-card.high {
      border-left-color: #ea580c;
      background: #fff7ed;
    }
    
    .summary-card.medium {
      border-left-color: #f59e0b;
      background: #fffbeb;
    }
    
    .summary-card.low {
      border-left-color: #10b981;
      background: #f0fdf4;
    }
    
    .summary-card h3 {
      font-size: 2em;
      margin-bottom: 5px;
    }
    
    .finding {
      background: #f9fafb;
      padding: 20px;
      margin: 15px 0;
      border-radius: 5px;
      border-left: 5px solid #6b7280;
    }
    
    .finding.critical {
      border-left-color: #dc2626;
    }
    
    .finding.high {
      border-left-color: #ea580c;
    }
    
    .finding.medium {
      border-left-color: #f59e0b;
    }
    
    .finding.low {
      border-left-color: #10b981;
    }
    
    .finding h3 {
      color: #1f2937;
      margin-bottom: 10px;
    }
    
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 0.85em;
      font-weight: 600;
      margin-right: 8px;
    }
    
    .badge.critical {
      background: #dc2626;
      color: white;
    }
    
    .badge.high {
      background: #ea580c;
      color: white;
    }
    
    .badge.medium {
      background: #f59e0b;
      color: white;
    }
    
    .badge.low {
      background: #10b981;
      color: white;
    }
    
    .badge.info {
      background: #6b7280;
      color: white;
    }
    
    footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
    }
  `.trim();
}

/**
 * Generate summary section HTML
 * 
 * @param summary - Report summary data
 * @returns HTML string
 */
function generateSummaryHTML(summary: ReportSummary): string {
  return `
    <div class="summary-grid">
      <div class="summary-card">
        <h3>${summary.totalPackages}</h3>
        <p>Total Packages</p>
      </div>
      <div class="summary-card critical">
        <h3>${summary.criticalFindings}</h3>
        <p>Critical Findings</p>
      </div>
      <div class="summary-card high">
        <h3>${summary.highFindings}</h3>
        <p>High Findings</p>
      </div>
      <div class="summary-card medium">
        <h3>${summary.mediumFindings}</h3>
        <p>Medium Findings</p>
      </div>
      <div class="summary-card low">
        <h3>${summary.lowFindings}</h3>
        <p>Low Findings</p>
      </div>
      <div class="summary-card">
        <h3>${summary.reachableVulnerabilities}</h3>
        <p>Reachable Vulnerabilities</p>
      </div>
    </div>
  `;
}

/**
 * Generate findings section HTML
 * 
 * @param findings - Array of findings
 * @returns HTML string
 */
function generateFindingsHTML(findings: Finding[]): string {
  if (findings.length === 0) {
    return '<p>No vulnerabilities found. Great job! 🎉</p>';
  }
  
  return findings.map(finding => `
    <div class="finding ${escapeHtml(finding.riskScore.riskLevel.toLowerCase())}">
      <h3>
        <span class="badge ${escapeHtml(finding.riskScore.riskLevel.toLowerCase())}">${escapeHtml(finding.riskScore.riskLevel)}</span>
        ${escapeHtml(finding.title)}
      </h3>
      <p><strong>Package:</strong> ${escapeHtml(finding.package.name)}@${escapeHtml(finding.package.version)}</p>
      <p><strong>Vulnerability:</strong> ${escapeHtml(finding.vulnerability.id)}</p>
      <p><strong>Summary:</strong> ${escapeHtml(finding.vulnerability.summary)}</p>
      <p><strong>Risk Score:</strong> ${finding.riskScore.score}/100</p>
      <p><strong>Reasoning:</strong> ${escapeHtml(finding.riskScore.reasoning)}</p>
      <div style="margin-top: 15px;">
        <strong>Remediation:</strong>
        <ul style="margin-left: 20px; margin-top: 5px;">
          ${finding.remediation.map(step => `
            <li>${escapeHtml(step.description)} (Effort: ${escapeHtml(step.effort)})</li>
          `).join('')}
        </ul>
      </div>
    </div>
  `).join('');
}

/**
 * Write HTML report to file
 *
 * @param _html - HTML content
 * @param outputPath - Path to write the report
 */
export async function writeHTMLReport(_html: string, outputPath: string): Promise<void> {
  // TODO: Implement file writing
  console.log(`Writing HTML report to ${outputPath}`);
}

/**
 * Generate JSON report
 * 
 * @param report - Complete report data
 * @returns JSON string
 */
export function generateJSONReport(report: Report): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Write JSON report to file
 *
 * @param _json - JSON content
 * @param outputPath - Path to write the report
 */
export async function writeJSONReport(_json: string, outputPath: string): Promise<void> {
  // TODO: Implement file writing
  console.log(`Writing JSON report to ${outputPath}`);
}

// Made with Bob
